# Generated by Django 5.2.8 on 2025-12-08 11:52

from django.db import migrations


def convert_empty_to_null(apps, schema_editor):
    """Convert empty string values to NULL for country and city fields."""
    KYC = apps.get_model("accounts", "KYC")
    # Update all KYC records with empty strings to NULL
    KYC.objects.filter(country="").update(country=None)
    KYC.objects.filter(city="").update(city=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_update_kyc_status_to_not_filed"),
    ]

    operations = [
        migrations.RunPython(convert_empty_to_null, migrations.RunPython.noop),
    ]
