# Generated by Django 5.2.8 on 2025-12-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_convert_empty_country_city_to_null'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_records', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_records', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('supporter', 'Supporter'), ('admin', 'Admin')], default='creator', max_length=20),
        ),
    ]
