# Generated by Django 5.2.8 on 2025-12-08 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_kyc_city_alter_kyc_country_alter_user_role'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_records', to='cities_light.region'),
        ),
    ]
