# Generated by Django 5.2.8 on 2025-12-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_kyc_region'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_region', to='cities_light.subregion'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='cities_light.region'),
        ),
    ]
