# Generated by Django 5.2.8 on 2025-12-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_kyc_subregion_alter_kyc_city_alter_kyc_country_and_more'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subregion', to='cities_light.subregion'),
        ),
    ]
