# Generated by Django 5.2.8 on 2025-12-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_kyc_subregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='back_image',
            field=models.ImageField(blank=True, upload_to='kyc/documents/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='front_image',
            field=models.ImageField(blank=True, upload_to='kyc/documents/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie_with_document',
            field=models.ImageField(blank=True, upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('citizenship', 'Citizenship'), ('driver_license', 'Driver License'), ('passport', 'Passport')], max_length=50),
        ),
    ]
