# Generated by Django 5.2.8 on 2025-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_kyc_back_image_kyc_front_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='back_image',
            field=models.ImageField(blank=True, upload_to='private/kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='front_image',
            field=models.ImageField(blank=True, upload_to='private/kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie_with_document',
            field=models.ImageField(blank=True, upload_to='private/kyc/documents/'),
        ),
    ]
