# Generated by Django 5.2.8 on 2025-12-21 05:52

import root.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_kyc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='back_image',
            field=models.ImageField(blank=True, storage=root.storage.PrivateMediaStorage(), upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='front_image',
            field=models.ImageField(blank=True, storage=root.storage.PrivateMediaStorage(), upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie_with_document',
            field=models.ImageField(blank=True, storage=root.storage.PrivateMediaStorage(), upload_to='kyc/documents/'),
        ),
    ]
