# Generated by Django 6.0.1 on 2026-02-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_verified_user_is_verified'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='region',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='subregion',
        ),
        migrations.AddField(
            model_name='kyc',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='cities_light.region'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subregion', to='cities_light.subregion'),
        ),
    ]
