# Generated by Django 6.0.1 on 2026-01-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_verified_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('merchant', 'Merchant'), ('support', 'Support'), ('creator', 'Creator'), ('supporter', 'Supporter')], default='creator', max_length=20),
        ),
    ]
