# Generated by Django 6.0.1 on 2026-02-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_kyc_region_remove_kyc_subregion_kyc_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('merchant', 'Merchant'), ('support', 'Support'), ('creator', 'Creator'), ('supporter', 'Supporter')], default='creator', max_length=20),
        ),
    ]
