[project]
name = "coffee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=2.1.0",
    "dj-email-url>=1.0.6",
    "django>=5.2.8",
    "django-admin-honeypot-updated-2021>=1.2.0",
    "django-cities-light>=3.10.2",
    "django-cleanup>=9.0.0",
    "django-defender>=0.9.8",
    "django-jazzmin>=3.0.1",
    "django-ratelimit>=4.1.0",
    "django-redis>=6.0.0",
    "django-viewcomponent>=1.0.11",
    "environs[django]>=14.5.0",
    "marshmallow>=4.1.0",
    "pillow>=12.0.0",
    "psycopg2-binary>=2.9.9",
    "pydantic[email]>=2.10.0",
    "pydantic-extra-types>=2.10.0",
    "requests>=2.32.5",
    "whitenoise>=6.11.0",
    "django-turnstile>=0.1.2",
    "stripe>=11.4.0",
    "celery[redis]>=5.6.0",
    "flower>=2.0.1",
    "django-celery-results>=2.6.0",
    "sentry-sdk[django]>=2.48.0",
    "django-allow-cidr>=0.8.0",
]

[project.optional-dependencies]
production = [
    "django-tailwind>=4.4.1",
    "gunicorn>=23.0.0",
    "uvicorn>=0.38.0",
]
development = [
    "django-tailwind[cookiecutter,honcho,reload]>=4.4.1",
    "djlint>=1.36.4",
    "pre-commit>=4.3.0",
    "ruff>=0.14.2",
    "faker>=39.0.0",
    "django-debug-toolbar>=4.4.0",
]

[tool.ruff]
line-length = 99
force-exclude = true
extend-exclude = ["migrations"]

[tool.ruff.lint]
preview=true
extend-select = ["C", "E", "F", "I001", "PLR6301", "Q", "SIM", "T", "W"]
ignore = ["SIM108"]


[tool.ruff.format]
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 20

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"
