[project]
name = "coffee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=2.1.0",
    "dj-email-url>=1.0.6",
    "django>=5.2.7",
    "django-jazzmin>=3.0.1",
    "djlint>=1.36.4",
    "environs>=14.4.0",
    "gunicorn>=23.0.0",
    "pillow>=12.0.0",
    "pre-commit>=4.3.0",
    "psycopg2-binary>=2.9.9",
    "requests>=2.32.5",
    "ruff>=0.14.2",
    "uvicorn>=0.38.0",
    "whitenoise>=6.11.0",
]

[tool.ruff]
line-length = 99
force-exclude = true
extend-exclude = ["migrations"]

[tool.ruff.lint]
preview=true
extend-select = ["C", "E", "F", "I001", "PLR6301", "Q", "SIM", "T", "W"]

[tool.ruff.format]
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 20

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"
