services:
  db:
    container_name: postgis
    image: postgis/postgis:17-3.5
    env_file: .env
    volumes:
      - postgis-data:/var/lib/postgresql/data
    networks:
      - external-services


networks:
  external-services:
    external: true

volumes:
  postgis-data:
    name: postgis-data
