# Generated by Django 5.2.7 on 2025-11-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('payments', '0001_initial'), ('payments', '0002_remove_supporttransaction_supporter_email'), ('payments', '0003_paymentgateway'), ('payments', '0004_paymentgateway_brand_color'), ('payments', '0005_paymentgateway_failure_url_and_more')]

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('benefits', models.TextField()),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='creators.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporter_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.membership')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporter_name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_transactions', to='creators.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField()),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='payments.supporttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('bank_account', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='creators.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('merchant_id', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('base_url', models.URLField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_icons/')),
                ('description', models.TextField(blank=True)),
                ('brand_color', models.CharField(default='#000000', max_length=7)),
                ('failure_url', models.URLField(blank=True)),
                ('sandbox_url', models.URLField(blank=True)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('success_url', models.URLField(blank=True)),
            ],
        ),
    ]
