# Generated by Django 5.2.7 on 2025-11-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporttransaction',
            name='supporter_email',
        ),
    ]
