# Generated by Django 5.2.7 on 2025-11-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='brand_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
