# Generated by Django 5.2.7 on 2025-11-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentgateway_brand_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='failure_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='sandbox_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='success_url',
            field=models.URLField(blank=True),
        ),
    ]
