# Generated by Django 5.2.8 on 2025-12-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_squashed_0005_paymentgateway_failure_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_details',
            field=models.CharField(blank=True, help_text='Bank account number, eSewa ID, or Khalti number', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
