# Generated by Django 5.2.8 on 2026-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_withdrawal_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='gateway',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supporttransaction',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe')], default='bank', max_length=20),
        ),
    ]
