# Generated by Django 5.2.8 on 2026-01-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_paymentlog_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('ambiguous', 'Ambiguous'), ('not_found', 'Not Found'), ('canceled', 'Canceled'), ('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('signature_mismatch', 'Signature Mismatch'), ('api_complete', 'API Complete'), ('api_pending', 'API Pending'), ('api_error', 'API Error'), ('api_unknown', 'API Unknown'), ('unknown_status', 'Unknown Status'), ('session_created', 'Session Created'), ('session_creation_failed', 'Session Creation Failed'), ('completed', 'Completed'), ('payment_not_completed', 'Payment Not Completed'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
