# Generated by Django 6.0.1 on 2026-01-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymentlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='gateway',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('ambiguous', 'Ambiguous'), ('not_found', 'Not Found'), ('canceled', 'Canceled'), ('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('signature_mismatch', 'Signature Mismatch'), ('api_complete', 'API Complete'), ('api_pending', 'API Pending'), ('api_error', 'API Error'), ('api_unknown', 'API Unknown'), ('unknown_status', 'Unknown Status'), ('session_created', 'Session Created'), ('session_creation_failed', 'Session Creation Failed'), ('completed', 'Completed'), ('payment_not_completed', 'Payment Not Completed'), ('cancelled', 'Cancelled'), ('paypal_order_created', 'PayPal Order Created'), ('paypal_order_creation_failed', 'PayPal Order Creation Failed'), ('paypal_payment_captured', 'PayPal Payment Captured'), ('paypal_payment_not_captured', 'PayPal Payment Not Captured')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supporttransaction',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='bank', max_length=20),
        ),
    ]
