# Generated by Django 6.0.1 on 2026-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_remove_creatorprofile_page_url'),
        ('payments', '0009_alter_paymentlog_gateway_alter_paymentlog_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supporttransaction',
            index=models.Index(fields=['payment_status', 'created_at'], name='payments_su_payment_8bd3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='supporttransaction',
            index=models.Index(fields=['payment_status', 'supporter_name'], name='payments_su_payment_23881c_idx'),
        ),
        migrations.AddIndex(
            model_name='supporttransaction',
            index=models.Index(fields=['creator', 'payment_status'], name='payments_su_creator_be2b77_idx'),
        ),
    ]
