# Generated by Django 6.0.1 on 2026-01-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_supporttransaction_payments_su_payment_8bd3ae_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='gateway',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='supporttransaction',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
