# Generated by Django 5.2.8 on 2025-12-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this template', max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('newsletter_verification', 'Newsletter Verification'), ('newsletter_welcome', 'Newsletter Welcome'), ('user_registration', 'User Registration'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('html_content', models.TextField(help_text='HTML content with template variables')),
                ('text_content', models.TextField(blank=True, help_text='Plain text content (optional, auto-generated if empty)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='emails_emai_name_dfce91_idx'), models.Index(fields=['template_type'], name='emails_emai_templat_8ab307_idx'), models.Index(fields=['is_active'], name='emails_emai_is_acti_1244cf_idx')],
            },
        ),
    ]
