# Generated by Django 5.2.8 on 2026-01-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('newsletter_verification', 'Newsletter Verification'), ('newsletter_welcome', 'Newsletter Welcome'), ('user_registration', 'User Registration'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('payment_success_creator', 'Payment Success Creator'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
    ]
