name: Push image

on:
  push:
    branches:
      - develop
      - staging
      - latest
    tags:
      - v*
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

env:
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/merocoffee
  DOCKER_BUILDKIT: 1

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Copy .env files
        run: cp .env.prod.example .env

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag merocoffee --target production \
            --progress=plain --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from $(echo $IMAGE_ID | tr '[A-Z]' '[a-z]'):develop

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo VERSION=$VERSION
          docker tag merocoffee $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
